// file: ./src/app/area/private/enum.ts
export enum PrivateAreaLayoutSlotEnum {
    SLOT_START_SIDE_BAR_EXTENSION = 'SLOT_START_SIDE_BAR_EXTENSION',
    SLOT_MAIN_HEADER_TOOLBAR_EXTENSION = 'SLOT_MAIN_HEADER_TOOLBAR_EXTENSION',
    SLOT_MAIN_FOOTER_TOOLBAR_EXTENSION = 'SLOT_MAIN_FOOTER_TOOLBAR_EXTENSION',
    
    SLOT_END_SIDE_BAR_TAB_LABEL = 'SLOT_END_SIDE_BAR_TAB_LABEL',
    SLOT_END_SIDE_BAR_TAB_BODY = 'SLOT_END_SIDE_BAR_TAB_BODY',

    SLOT_END_SIDE_BAR_FOOTER = 'SLOT_END_SIDE_BAR_FOOTER'
}