// file: tools/migration/schema.ts

/// <reference types="node" />

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const ROOT_DIR = process.cwd();

const TEMP_DIR = path.join(ROOT_DIR, '.tmp', 'drizzle-public-schema');
const TEMP_DRIZZLE_DIR = path.join(TEMP_DIR, 'drizzle');
const TEMP_CONFIG_FILE = path.join(TEMP_DIR, 'drizzle.public.config.ts');

const OUTPUT_FILE = path.join(ROOT_DIR, 'public', 'db', 'schema.sql');
const SCHEMA_STATIC_FILE = path.join(ROOT_DIR, 'public', 'db', 'schema.static.sql');

const SCHEMA_GLOBS = [
  './libs/src/**/entity.ts',
  './src/**/entity.ts',
];

function removeDir(dir: string): void {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, {
      recursive: true,
      force: true,
    });
  }
}

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, {
    recursive: true,
  });
}

function writeTempDrizzleConfig(): void {
  const config = `
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  dialect: 'sqlite',
  schema: ${JSON.stringify(SCHEMA_GLOBS, null, 2)},
  out: ${JSON.stringify(TEMP_DRIZZLE_DIR)},
});
`;

  fs.writeFileSync(TEMP_CONFIG_FILE, config.trimStart(), 'utf8');
}

function findSqlFiles(dir: string): string[] {
  const found: string[] = [];

  function walk(currentDir: string): void {
    const items = fs.readdirSync(currentDir);

    for (const item of items) {
      const fullPath = path.join(currentDir, item);
      const stat = fs.statSync(fullPath);

      if (stat.isDirectory()) {
        walk(fullPath);
        continue;
      }

      if (item.endsWith('.sql')) {
        found.push(fullPath);
      }
    }
  }

  if (fs.existsSync(dir)) {
    walk(dir);
  }

  found.sort();
  return found;
}

function readStaticSql(): string {
  if (!fs.existsSync(SCHEMA_STATIC_FILE)) {
    return '';
  }

  const sql = fs.readFileSync(SCHEMA_STATIC_FILE, 'utf8').trim();

  if (!sql) {
    return '';
  }

  return [
    '',
    '-- --------------------------------------------------',
    '-- Static SQL',
    '-- Source: public/db/schema.static.sql',
    '-- Use this for default seed data / static inserts',
    '-- --------------------------------------------------',
    sql,
    '',
  ].join('\n');
}

function buildSingleSqlFile(sqlFiles: string[]): string {
  const chunks: string[] = [];

  chunks.push('-- --------------------------------------------------');
  chunks.push('-- Auto-generated SQLite schema');
  chunks.push('-- Source: entity.ts files');
  chunks.push('-- Do not edit manually');
  chunks.push('-- --------------------------------------------------');
  chunks.push('');

  for (const file of sqlFiles) {
    const relative = path.relative(ROOT_DIR, file);
    const sql = fs.readFileSync(file, 'utf8').trim();

    if (!sql) {
      continue;
    }

    chunks.push('-- --------------------------------------------------');
    chunks.push(`-- ${relative}`);
    chunks.push('-- --------------------------------------------------');
    chunks.push(sql);
    chunks.push('');
  }

  const staticSql = readStaticSql();

  if (staticSql) {
    chunks.push(staticSql);
  }

  return chunks.join('\n').trim() + '\n';
}

function main(): void {
  removeDir(TEMP_DIR);
  ensureDir(TEMP_DIR);
  ensureDir(path.dirname(OUTPUT_FILE));

  writeTempDrizzleConfig();

  execFileSync(
    process.platform === 'win32' ? 'npx.cmd' : 'npx',
    [
      'drizzle-kit',
      'generate',
      '--config',
      TEMP_CONFIG_FILE,
      '--name',
      'public-schema',
    ],
    {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    },
  );

  const sqlFiles = findSqlFiles(TEMP_DRIZZLE_DIR);

  if (sqlFiles.length === 0) {
    throw new Error('No SQL file was generated by Drizzle Kit.');
  }

  const finalSql = buildSingleSqlFile(sqlFiles);

  fs.writeFileSync(OUTPUT_FILE, finalSql, 'utf8');

  console.log('');
  console.log(`Created: ${path.relative(ROOT_DIR, OUTPUT_FILE)}`);

  if (fs.existsSync(SCHEMA_STATIC_FILE)) {
    console.log(`Included: ${path.relative(ROOT_DIR, SCHEMA_STATIC_FILE)}`);
  }
}

main();