// ./env/production.env.ts
import { defaultEnvironment } from "./default.env";
const productionEnvironment: any = {
    NODE_ENV: 'production',

    BFW_API_SDK_JWT_ACCESS_TOKEN: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImF2MSJ9.eyJzdWIiOiJNUSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImluZm9AdGhhdHNlbmQuY29tIiwicm9sZV9pZCI6MSwidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTc4MTA4ODkwOCwiZXhwIjoxNzgxMTc1MzA4LCJhdWQiOiJBcHBsaWNhdGlvbiIsImlzcyI6IlRIQVRTRU5EIn0.TJxISOxqNwnGhiWFW5P_thcBKMF-wYHRTHe3_ZxM9gU5CHi7nGtXfsASyvg6o9c3Zo9JxrF6Ha0kGIGPmCyllJnzvLGHuWcxmg5n5hROK_4Z-KD7Ovs6bbKJatZWnlhADqE87bBr5ewS3L_REMQlSuuiBEHECAJNP2kZnZvductGWxEEC2yg6Bo3gJHw_VJWHbGvo_9UEbaRIMC8MtY0dL4vKPoyidx4XnoYs1UxpwNnAYYY2uXfv1kDR7HhIgcQ2QId_LaEmj_1VPoXc5oCrDxdXyT4EKDj2vW-1LK0uC6xAinNQHXI35LW7RZFTdvLi5ijQIuarA6wYjAxeZJ4hg',
    BFW_API_SDK_JWT_REFRESH_TOKEN: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJ2MSJ9.eyJzdWIiOiJNUSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImluZm9AdGhhdHNlbmQuY29tIiwicm9sZV9pZCI6MSwidHlwZSI6InJlZnJlc2hfdG9rZW4iLCJpYXQiOjE3ODEwODg5MDgsImV4cCI6MTc4MTY5MzcwOCwiYXVkIjoiQXBwbGljYXRpb24iLCJpc3MiOiJUSEFUU0VORCJ9.b3HMY83JVqE5VubFxzn893-FB4MCWG8y0d5Xnqir4G3NN3y4t7Zry8qaIgVNOckY9Zzm4C00ENUQADXRJov5jbXRNRZRQYDmeJTFzI-IQSzVSARECnWygVVIviO39LxFQ5JMWIbr17kKXm31xa_9x0FYOISuDztPa7E8TM5AmLoBgwHN0mqzHMAqqxgC7bLA2cO-NbDF-JJxV7X2kwb3MjogfnLbvmIjaNJPidb6JgU4DbeaXkj_1P_9zSkWhi1a0O_JcVPQBldYx8vRI-0YIC9VE9TfBPaBRfbJAL2zPqk37fUdv7VfeZNGwlgGCWrBjRMVoJYbonVJmhVulNhsZA',

    BFW_API_SDK_GRAPHQL_URL: 'https://bfw-nestjs-microservice-api.thatsend.app/graphql',
    BFW_API_SDK_REST_URL: 'https://bfw-nestjs-microservice-api.thatsend.app/rest',
    BFW_API_SDK_WS_URL: 'https://bfw-nestjs-microservice-ws.thatsend.app',
};
export const environment: any = {...defaultEnvironment, ...productionEnvironment};